casino:
  staff-permission: "op"                                              # Permission til brug af /ca
  prefix: "&8&l[ &c&lCASINO &8&l] "                                   # Prefix til at med craten at gøre.
  lore:                                                               # Lore til items når man vil se hvilke items craten har. Sørg for at have %chance% med.
    - '&7'
    - '&8┃ &7Chance: &f%chance%%'
  top_row: "&c"                                                       # Farve på top glas i GUI
  bottom_row: "&f"                                                    # Farve på bund glas i GUI
  reward-msg: "&8&l✪ &f&lDU VANDT &c&l%antal%x %item% &8&l✪"          # Hologramet når man får sin præmie.
  crateopen-msg: "&cDu er allerede i gang med at åbne en crate!"      # Hvis personen allerede er igang med at åbne en crate.


  # CRATE DELEN (ALT SKAL VÆRE DER)
  # ➜ Skal der laves en mere crate skriv -1: (Self følg rækkefølgen i numre)
  # ➜ Block = Hvilken block cratens skal være. Hvis du ikke har skrevet det rigtige fungere det ikke. (Alt med store bogstaver)
  # ➜ Head = Hvilket hoved det skal flyve op af kisten.

  # REWARDS DELEN
  #
  # DE TING DER SKAL VÆR DER.
  # ➜ Skal der laves en mere reward skriv -1: (Self følg rækkefølgen i numre)
  # ➜ material = Skal være der. Hvilken block man der skal bruges til rewarden.
  # ➜ guiName = Hvad den skal hedde i GUI.
  # ➜ Antal = Skal være der også selvom du kun skal have 1.
  #
  # HVAD DU KAN SÆTTE PÅ
  # ➜ Data = vil sige f.eks. på en farve uld. Hedder ID'et på den item 35:(14) Dataen er derfor 14.
  # ➜ Enchants = Du kan add enchants til items, men sørg for at kig på listen for at det er den rigtige.
  # Når du skal add en enchant skriver du:
  # enchants:
  #    1: "KNOCKBACK 5"
  #    2: "OXYGEN 2"
  # Navne på enchants kan ses i #crate (Discord kanal) Flere eksempler på hvordan det er gjort neden under.


  crates:
    - 1:
      block: "ENDER_CHEST"
      head: "http://textures.minecraft.net/texture/588149e56cde02eee620982884b893634756be9141f2e2777b51cb0a66c31dce"
      rewards:
        - 1:
          material: "STONE_AXE"
          guiName: "&8&lSTEN &f&lØKSE"
          antal: 1
          chance: 30
        - 2:
          material: "SPONGE"
          guiName: "&e&lSVAMP"
          antal: 2
          chance: 20
        - 3:
          material: "WOOL"
          guiName: "&c&lRED &f&lWOOL"
          data: 14
          enchants:
            1: "KNOCKBACK 5"
          antal: 2
          chance: 50

    - 2:
      block: "BEACON"
      head: "http://textures.minecraft.net/texture/de4baa04ba6c1c6baccd9972858dcbbf8a61d773871931319fb3f9b905b46651"
      rewards:
        - 1:
          material: "INK_SACK"
          guiName: "&8&lBLÆK"
          antal: 1
          chance: 30
        - 2:
          material: "STONE"
          guiName: "&7&lSTEN"
          antal: 2
          chance: 70


